local mcd_id = "dude_where_is_my_gear"

function on_mcm_load()
	local op = { id= mcd_id ,gr={}} -- {id = mcd_id, type = "slide", link = "ui_options_slider_player", text = "ui_mcm_menu_" .. mcd_id, size = {512, 50}, spacing = 20},
	
	local presets = {id = "presets", text = "ui_mcm_dwimg_presets", gr = {}}
	table.insert(op.gr, presets)
	
	local default_presets = {id = "default_presets", text = "ui_mcm_dwimg_default_presets", sh = true, gr = {
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_def_presets", clr = {255, 255 ,255 ,255}, },
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_def_presets_dif", clr = {255, 255 ,255 ,255}, },		
		{id = "def_preset_money",              		type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_money_off", "preset_off"}, {"preset_money_easy", "preset_easy"}, {"preset_money_medium", "preset_medium"}, {"preset_money_hard", "preset_hard"}, {"preset_money_hardcore", "preset_hardcore"} } , def="n"},
		{id = "def_preset_condition",              	type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_condition_off", "preset_off"}, {"preset_condition_easy", "preset_easy"}, {"preset_condition_medium", "preset_medium"}, {"preset_condition_hard", "preset_hard"}, {"preset_condition_very_hard", "preset_very_hard"} } , def="n"},
		{id = "def_preset_item_loss_basic",        	type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_item_loss_basic_off", "preset_off"}, {"preset_item_loss_basic_easy", "preset_easy"}, {"preset_item_loss_basic_medium", "preset_medium"}, {"preset_item_loss_basic_hard", "preset_hard"}, {"preset_item_loss_basic_hardcore", "preset_hardcore"} } , def="n"},
		{id = "def_preset_item_loss_core",        	type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_item_loss_core_off", "preset_off"}, {"preset_item_loss_core_easy", "preset_easy"}, {"preset_item_loss_core_medium", "preset_medium"}, {"preset_item_loss_core_hard", "preset_hard"}, {"preset_item_loss_core_hardcore", "preset_hardcore"} } , def="n"},
		{id = "def_preset_item_loss_scaling",      	type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_item_loss_scaling_off", "preset_off"}, {"preset_item_loss_scaling_easy", "preset_easy"}, {"preset_item_loss_scaling_medium", "preset_medium"}, {"preset_item_loss_scaling_hard", "preset_hard"}, {"preset_item_loss_scaling_to_100_easy", "preset_100_easy"}, {"preset_item_loss_scaling_to_100_medium", "preset_100_medium"}, {"preset_item_loss_scaling_to_100_hard", "preset_100_hard"} } , def="n"},
		{id = "def_preset_item_punish",        		type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_item_punish_off", "preset_off"}, {"preset_item_punish_easy", "preset_easy"}, {"preset_item_punish_medium", "preset_medium"}, {"preset_item_punish_hard", "preset_hard"}, {"preset_item_punish_hardcore", "preset_hardcore"} } , def="n"},		
		{id = "def_preset_ignore",      			type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_ignore_all", "preset_ignore_all"},{"preset_ignore_midway", "preset_ignore_midway"}, {"preset_ignore_basic", "preset_ignore_basic"}, {"preset_ignore_nothing", "preset_ignore_nothing"} } , def="n"},
		{id = "def_preset_protection",      		type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_protection_off", "preset_off"}, {"preset_protection_early", "preset_protection_early"},{"preset_protection_easy", "preset_easy"}, {"preset_protection_medium", "preset_medium"}, {"preset_protection_hard", "preset_hard"} } , def="n"},
		{id = "def_preset_character",        		type = "list", val = 0, content = {{"n", "no_preset"}, {"preset_character_off", "preset_off"}, {"preset_character_easy", "preset_easy"}, {"preset_character_medium", "preset_medium"}, {"preset_character_hard", "preset_hard"} } , def="n"},
	}}
	table.insert(presets.gr, default_presets)
	
	local custom_presets = {id = "custom_presets", text = "ui_mcm_dwimg_custom_presets", sh = true, gr = {
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_cst_presets", clr = {255, 255 ,255 ,255}, },
		{id = "chosen_preset",                		type = "list", val = 2, content = {{1, "preset_1"}, {2, "preset_2"}, {3, "preset_3"}, {4, "preset_4"}, {5, "preset_5"} } , def=0},
		{type = "title", text = ""},
		{id = "save_preset",		              	type = "check", val = 1, def = false},
		{id = "load_preset",		              	type = "check", val = 1, def = false},
		{type = "title", text = ""},		
		{id = "cst_preset_money",	              	type = "check", val = 1, def = true},
		{id = "cst_preset_condition",	            type = "check", val = 1, def = true},
		{id = "cst_preset_item_loss",	            type = "check", val = 1, def = true},
		{id = "cst_preset_ignore",	    	        type = "check", val = 1, def = true},
		{id = "cst_preset_protection", 	        	type = "check", val = 1, def = true},
		{id = "cst_preset_item_punish",    	        type = "check", val = 1, def = true},
		{id = "cst_preset_character",	   	        type = "check", val = 1, def = true},
		{id = "cst_preset_day_time",	   	        type = "check", val = 1, def = true},
		{id = "cst_preset_old_stuff",	   	        type = "check", val = 1, def = true},
	}}
	table.insert(presets.gr, custom_presets)
	
	local money  = {id = "money", text = "ui_mcm_dwimg_money", sh = true, gr = {
		{id = "min_money_percentage",               type = "track", val = 2, min=0.00, max=1.00, step=0.01, def = 0},
		{id = "max_money_percentage",               type = "track", val = 2, min=0.00, max=1.00, step=0.01, def = 0},
		{id = "min_money_to_drop_percentage",       type = "track", val = 2, min=0.00, max=1.00, step=0.01, def = 0},
		{id = "max_money_to_drop_percentage",       type = "track", val = 2, min=0.00, max=1.00, step=0.01, def = 0},
		{type = "title", text = ""},
		{id = "min_money_to_keep_inventory",		type = "input", val = 2, min=0, max=999999, def = 0},
		{id = "min_money_to_keep_general",		    type = "input", val = 2, min=0, max=999999, def = 0},
		{type = "title", text = ""},
		{id = "max_lost_money",					    type = "input", val = 2, min=0, max=999999, def = 999999},
		{id = "money_y_rank",                 		type = "track", val = 2, min=0,    max=10,  step=0.1,    def = 0},	
	}}
	table.insert(op.gr, money)
	
	local condition = {id = "condition", text = "ui_mcm_dwimg_condition", gr = {}}
	table.insert(op.gr, condition)
	
	local condition_ga = {id = "condition_ga", text = "ui_mcm_dwimg_condition_ga", sh = true, gr = {
		{id = "min_condition_lose",                 type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "max_condition_lose",                 type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "min_weapon_condition",            	type = "track", val = 2, min=1,    max=100,  step=1,    def = 1},
		{id = "min_armor_condition",            	type = "track", val = 2, min=1,    max=100,  step=1,    def = 1},	
		{id = "part_break_chance",	            	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "condition_unequipped",               type = "check", val = 1, def = false},
		{id = "spread_weapon_condition",            type = "check", val = 1, def = true},

	}}
	table.insert(condition.gr, condition_ga)
	
	local condition_o = {id = "condition_o", text = "ui_mcm_dwimg_condition_o", sh = true, gr = {
		{id = "min_condition_lose2",                type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "max_condition_lose2",                type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "condition_melee",               		type = "check", val = 1, def = false},
		{id = "condition_perk_artefact",       		type = "check", val = 1, def = false},
		{id = "condition_stat_artefact",       		type = "check", val = 1, def = false},
		{id = "condition_pelt",                		type = "check", val = 1, def = false},
	}}
	table.insert(condition.gr, condition_o)
	
	local item_loss = {id = "item_loss", text = "ui_mcm_dwimg_item_loss", gr = {}}
	table.insert(op.gr, item_loss)
	
	local lose_keep = {id = "lose_keep", text = "ui_mcm_dwimg_lose_keep", sh = true, gr = {
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_loss_desc", clr = {255, 255 ,255 ,255}, },
		{id = "desc_scaling_1",						type = "desc", text = "ui_mcm_dwimg_scaling_1_desc", clr = {255, 255 ,255 ,255}, },
		{id = "desc_scaling_2", 					type = "desc", text = "ui_mcm_dwimg_scaling_2_desc", clr = {150, 213, 255,255}, },
		{id = "chance_of_losing_guns",	 			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_guns_scaled",		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_guns_chance",          			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_guns_chance_scaled",       		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},		
		{id = "chance_of_losing_gun_attachments",	 		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_gun_attachments_scaled", 	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_gun_attachment_chance",     			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_gun_attachment_chance_scaled",     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_outfits",          	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_outfits_scaled",   	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_outfit_chance",        			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_outfit_chance_scaled", 			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_artefacts",         type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_artefacts_scaled",	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_artefact_chance",        		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_artefact_chance_scaled",   		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_devices",         	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_devices_scaled",   	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_device_chance",        			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_device_chance_scaled",        	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_kits",    	 		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_kits_scaled",    	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_kits_chance",     				type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_kits_chance_scaled",     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_tools",    	 		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_tools_scaled",    	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_tools_chance",     				type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_tools_chance_scaled",     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_explosives",	 		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_explosives_scaled",	 	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_explosives_chance",		     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_explosives_chance_scaled",		    type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_ammo",     			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_ammo_scaled",     	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_ammo_chance",     				type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_ammo_chance_scaled",     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_medics",    	 	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_medics_scaled",    	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_medics_chance",     			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_medics_chance_scaled",     		type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "chance_of_losing_items",             type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "chance_of_losing_items_scaled",      type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_misc_items_chance",             type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_misc_items_chance_scaled",      type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
	}}
	table.insert(item_loss.gr, lose_keep)
	
	local loss_scaling = {id = "loss_scaling", text = "ui_mcm_dwimg_loss_scaling", sh = true, gr = {
		{id = "enable_scale",        	     	  	type = "check", val = 1, def = false},
		{id = "scaling_exponent",        			type = "track", val = 2, min=0.1,    max=4,  step=0.1,    def = 1.0},
		{type = "title", text = ""},
		{id = "rank_scale_from",         	        type = "track", val = 2, min=0,    max=100000,  step=1000,    def = 0},
		{id = "rank_scale_until",         	        type = "track", val = 2, min=0,    max=100000,  step=1000,    def = 0},
		{type = "title", text = ""},
		{id = "rank_scale_from2",         	        type = "track", val = 2, min=0,    max=100000,  step=1000,    def = 0},
		{id = "rank_scale_until2",         	        type = "track", val = 2, min=0,    max=100000,  step=1000,    def = 0},

	}}
	table.insert(item_loss.gr, loss_scaling)
	
	local item_punish = {id = "item_punish", text = "ui_mcm_dwimg_item_punish", gr = {}}
	table.insert(op.gr, item_punish)
	
	local item_break = {id = "item_break", text = "ui_mcm_dwimg_item_break", sh = true, gr = {
		{id = "broken_gun_chance",                	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "broken_armor_chance",             	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_gun_armor_parts_chance",       	type = "track", val = 2, min=0,    max=100,  step=1,    def = 100},
		{id = "keep_upgrade_chance",	            type = "track", val = 2, min=0,    max=100,  step=1,    def = 100},
		{type = "title", text = ""},
		{id = "broken_device_chance",             	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "keep_device_part_chance",            type = "track", val = 2, min=0,    max=100,  step=1,    def = 100},
	}}
	table.insert(item_punish.gr, item_break)

	local break_o = {id = "break_o", text = "ui_mcm_dwimg_break_o", sh = true, gr = {
		{id = "remove_upgrade_chance",            	type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "downgrade_chance",        			type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
	}}
	
	local ignore = {id = "ignore", text = "ui_mcm_dwimg_ignore", sh = true, gr = {
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_ignore_desc", clr = {255, 255 ,255 ,255}, },
		{id = "ignore_pda",			     			type = "track", val = 2, min=0,    max=3, step=1,   def = 0},
		{id = "ignore_backpack",			     	type = "track", val = 2, min=0,    max=5, step=1,   def = 0},			
		{id = "ignore_detector",	     			type = "track", val = 2, min=0,    max=4, step=1,   def = 0},
		{id = "ignore_torch_nvg",			     	type = "track", val = 2, min=0,    max=5, step=1,   def = 0},
		{id = "ignore_knife",			  		   	type = "track", val = 2, min=0,    max=9, step=1,   def = 0},
		{id = "ignore_axe",			     			type = "check", val = 1, def = false},
		{id = "ignore_binoculars",		          	type = "check", val = 1, def = false},
		{id = "ignore_special_equipment",          	type = "check", val = 1, def = false},
	}}
	table.insert(op.gr, ignore)
	
	table.insert(item_punish.gr, break_o)
	local protection = {id = "protection", text = "ui_mcm_dwimg_protection", sh = true, gr = {
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_exemption1_desc", clr = {255, 255 ,255 ,255}, },	
		{id = "max_rank_exemption",     			type = "input", val = 2, min=0, max=999999,  def = 0},
		{id = "gained_rank_exemption",     			type = "input", val = 2, min=0, max=999999,  def = 0},
		{id = "max_time_exemption",     			type = "input", val = 2, min=0, max=2400,  def = 0},
		{id = "passed_time_exemption",     			type = "input", val = 2, min=0, max=2400,  def = 0},
		
		{id = "desc_mcm", 							type = "desc", text = "ui_mcm_dwimg_exemption2_desc", clr = {255, 255 ,255 ,255}, },	
		{id = "max_rank_exemption2",     			type = "input", val = 2, min=0,    max=5000, def = 0},
		{id = "gained_rank_exemption2",     		type = "input", val = 2, min=0, max=999999,  def = 0},
		{id = "max_time_exemption2",     			type = "input", val = 2, min=0, max=2400,  def = 0},
		{id = "passed_time_exemption2",     		type = "input", val = 2, min=0, max=2400,  def = 0},
		{type = "title", text = ""},
		{id = "exemption_everything",         	    type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},		
		{id = "exemption_money",                	type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_guns",                		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_gun_attachements",    		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_outfits",                	type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_artefacts",           		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_device",                	type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_kit",                		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_tools",               		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_explosives",          		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_ammo",                		type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_medics",                	type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},
		{id = "exemption_misc",         	       	type = "list", val = 2, content={ {0,"no_protection"} , {1,"protection_a"}, {2,"protection_b"}}, def=0},		
	}}
	table.insert(op.gr, protection)

	local character = {id = "character", text = "ui_mcm_dwimg_character", sh = true, gr = {
		{id = "quest_fail_chance", 			    	type = "track", val = 2, min=0,    max=100, step=1,   def = 0},
		{id = "rank_loss", 			    			type = "track", val = 2, min=0.00,    max=100, step=1,   def = 0},
		{type = "title", text = ""},	
		{id = "desc_mcm2", 							type = "desc", text = "ui_mcm_dwimg_goodwill_desc", clr = {255, 255 ,255 ,255}, },		
		{id = "goodwill_loss_flat",	    			type = "track", val = 2, min=0,    max=1000, step=10,   def = 0},
		{id = "goodwill_loss_percent",	   			type = "track", val = 2, min=0,    max=100, step=1,   def = 0},
		{id = "min_goodwill",		    			type = "track", val = 2, min=-3000,    max=3000, step=50,   def = 0},
		{type = "title", text = ""},
		{id = "goodwill_enemies",					type = "check", val = 1, def = false},	
		{id = "goodwill_loss_flat_e",    			type = "track", val = 2, min=0,    max=1000, step=10,   def = 0},
		{id = "goodwill_loss_percent_e",   			type = "track", val = 2, min=0,    max=100, step=1,   def = 0},
		{id = "min_goodwill_e",		    			type = "track", val = 2, min=-3000,    max=3000, step=50,   def = 0},
		{type = "title", text = ""},
		{id = "goodwill_neutrals",					type = "check", val = 1, def = false},	
		{id = "goodwill_loss_flat_n",    			type = "track", val = 2, min=0,    max=1000, step=10,   def = 0},
		{id = "goodwill_loss_percent_n",   			type = "track", val = 2, min=0,    max=100, step=1,   def = 0},
		{id = "min_goodwill_n",		    			type = "track", val = 2, min=-3000,    max=3000, step=50,   def = 0},
		{type = "title", text = ""},
		{id = "goodwill_friends",					type = "check", val = 1, def = false},	
		{id = "goodwill_loss_flat_f",    			type = "track", val = 2, min=0,    max=1000, step=10,   def = 0},
		{id = "goodwill_loss_percent_f",   			type = "track", val = 2, min=0,    max=100, step=1,   def = 0},
		{id = "min_goodwill_f",		    			type = "track", val = 2, min=-3000,    max=3000, step=50,   def = 0},	
	}}
	table.insert(op.gr, character)

	local day_time = {id = "day_time", text = "ui_mcm_dwimg_day_time", gr = {}}
	table.insert(op.gr, day_time)

	local time_skip = {id = "time_skip", text = "ui_mcm_dwimg_time_skip", sh = true, gr = {
		{id = "min_time_skip",	     				type = "track", val = 2, min=0,    max=96, step=1,   def = 0},
		{id = "max_time_skip",	     				type = "track", val = 2, min=0,    max=96, step=1,   def = 0},
		{type = "title", text = ""},
		{id = "enable_wake_hours",					type = "check", val = 1, def = false},			
		{id = "min_wake_hour",	     				type = "track", val = 2, min=0,    max=24, step=1,   def = 0},		
		{id = "max_wake_hour",	     				type = "track", val = 2, min=0,    max=24, step=1,   def = 24},
	}}
	table.insert(day_time.gr, time_skip)
	
	local sat_thirst = {id = "sat_thirst", text = "ui_mcm_dwimg_sat_thirst", sh = true, gr = {	
		{id = "satiety_loss_per_hour",	            type = "track", val = 2, min=0.0,    max=10.00,  step=0.1,    def = 0},
		{id = "min_satiety",      		            type = "track", val = 2, min=1,    max=100,  step=1,    def = 100},
		{id = "min_thirst",      		            type = "track", val = 2, min=1,    max=100,  step=1,    def = 100},
	}}
	table.insert(day_time.gr, sat_thirst)

	local old_stuff = {id = "old_stuff", text = "ui_mcm_dwimg_old_stuff", sh = true, gr = {
		{id = "min_health",      		            type = "track", val = 2, min=1,    max=100,  step=1,    def = 100},
		{id = "max_health",      		            type = "track", val = 2, min=1,    max=100,  step=1,    def = 100},
		{id = "full_heal_chance",                   type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{id = "full_satiety_chance",                type = "track", val = 2, min=0,    max=100,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "remove_previous_stash",              type = "track",	val = 2, min=0,    max=10,  step=1,    def = 0},
		{type = "title", text = ""},
		{id = "use_sleep_respawn",              	type = "check", val = 1, def = false},
		{id = "use_campfire_respawn",               type = "check", val = 1, def = false},
		{id = "use_stash_respawn",              	type = "check", val = 1, def = false},
	}}
	table.insert(op.gr, old_stuff)
	
	local debug = {id = "debug", text = "ui_mcm_dwimg_debug", sh = true, gr = {
		{id = "display_issue",              		type = "check", val = 1, def = true},
		{id = "use_dwimglog",	                 	type = "check", val = 1, def = false},
		{id = "print_preset",	                 	type = "check", val = 1, def = false},
		{id = "edit_preset",	                 	type = "check", val = 1, def = false},
	}}
	table.insert(op.gr, debug)
	
	--local test = {id = "test", text = "#ui_mcm_dwimg_old_test", sh = true, gr = {}}
	--table.insert(old_stuff.gr, test) 
	
    return op
end
    
function get_config(key)
	if ui_mcm then 
		if ui_mcm.get(mcd_id .. "/" .. key) == nil then
			printf("DUDMCM nil: " .. key .. "\n")
		elseif ui_mcm.get(mcd_id .. "/debug/print_preset") then
			printf(key .. "\t = \t" .. tostring(ui_mcm.get(mcd_id .. "/" .. key)))
		end
		--printf("dudmcm for " .. tostring(key) .. " with " .. tostring(ui_mcm.get(mcd_id .. "/" .. key)) .. "\n")
		return ui_mcm.get(mcd_id .. "/" .. key)
	else 
		return defaults[key] --"dwimg_main/"..
	end 
end

function set_config(key, value)
	ui_mcm.set(mcd_id .. "/" .. key, value)
end
	

function load_def_preset(preset_name)
	local loading_preset = dwimg_def_presets.default_presets[tostring(preset_name)]
	dwimg_utils.print_dbg("Load def preset " .. tostring(preset_name))
	if loading_preset then
		for id, value in pairs(loading_preset) do
			set_config(id, value)
		end
		dwimg_utils.print_dbg("Loaded def preset " .. tostring(preset_name))
	end
		
end

function preset_backup()
	local dwimg_presets_ltx = ini_file_ex("dwimg_presets.ltx",true)
	if (not dwimg_presets_ltx:section_exist("init_from_backup")) and (not dwimg_presets_ltx:r_value("init_from_backup", "backup_completed") == true) then
		local dwimg_presets_backup_ltx = ini_file("gamedata\\configs\\presets\\dwimg_presets_backup.ltx")
		for i=1, 5 do
			if dwimg_presets_backup_ltx:section_exist(tostring(i)) then
				local n = dwimg_presets_backup_ltx:line_count(tostring(i))
				local l = 0
				while l <= n-1 do
					result, id, value = dwimg_presets_backup_ltx:r_line(tostring(i) , l , "", "")
					dwimg_presets_ltx:w_value(tostring(i), id, value)
					l = l + 1
				end	
			end
			i = i + 1
		end
		dwimg_presets_ltx:w_value("init_from_backup", "backup_completed", true)
		dwimg_presets_ltx:save()
	end
end

function handle_preset(preset_id, status, curr_setting_table, curr_setting_string, filter, filtered)
	--local dwimg_presets_ltx = ini_file_ex("presets\\dwimg_presets.ltx",true)
	local dwimg_presets_backup_ltx = ini_file_ex("gamedata\\configs\\presets\\dwimg_presets_backup.ltx",true)
	local dwimg_presets_ltx = ini_file_ex("dwimg_presets.ltx",true)
	local _curr_setting_string = curr_setting_string
	local _filtered = filtered
	dwimg_utils.print_dbg("Started handle preset curr_string " .. curr_setting_string)
	if  curr_setting_table["gr"] then
		if _curr_setting_string == "" and filter[curr_setting_table["id"]] == nil then
			_filtered = true
			dwimg_utils.print_dbg("Filtered " .. curr_setting_table["id"])
		end
		_curr_setting_string = _curr_setting_string .. curr_setting_table["id"] .. "/"
		dwimg_utils.print_dbg("Recursion curr_string " .. _curr_setting_string)
		handle_preset(preset_id, status, curr_setting_table["gr"], _curr_setting_string, filter, _filtered)
	else
		if curr_setting_table["id"] and curr_setting_table["type"] ~= "desc" then
			_curr_setting_string = _curr_setting_string .. curr_setting_table["id"]
			if status == 's' then
				dwimg_utils.print_dbg("Save curr_string " .. _curr_setting_string)
				if filtered == true then
					dwimg_presets_ltx:w_value(tostring(preset_id), _curr_setting_string, nil)
					dwimg_presets_ltx:save()
					dwimg_presets_backup_ltx:w_value(tostring(preset_id), _curr_setting_string, nil)
					dwimg_presets_backup_ltx:save()					
				else
					dwimg_presets_ltx:w_value(tostring(preset_id), _curr_setting_string, get_config(_curr_setting_string))
					dwimg_presets_ltx:save()
					dwimg_presets_backup_ltx:w_value(tostring(preset_id), _curr_setting_string, get_config(_curr_setting_string))
					dwimg_presets_backup_ltx:save()
				end
			elseif status == 'l' then
				if dwimg_presets_ltx:r_value(tostring(preset_id), _curr_setting_string) and dwimg_presets_ltx:r_value(tostring(preset_id), _curr_setting_string) ~= nil and filtered == false then
					dwimg_utils.print_dbg("Load curr_string " .. _curr_setting_string)
					set_config(_curr_setting_string, dwimg_presets_ltx:r_value(tostring(preset_id), _curr_setting_string))
				end
				if not dwimg_presets_ltx:r_value(tostring(preset_id), _curr_setting_string) then
					dwimg_utils.print_dbg("Not defined " .. _curr_setting_string .. " inside of " .. tostring(preset_id))
				end
		
			end
		else
			for i=1, #curr_setting_table do
				dwimg_utils.print_dbg("Recursion curr_string " .. _curr_setting_string)
				handle_preset(preset_id, status, curr_setting_table[i], _curr_setting_string, filter, _filtered)				
				i = i+1
			end
		end
	end
end