-- ==============================================================
-- SET RESPAWN POINT
-- ==============================================================

function save_position(stash_data)
    local sleep = dwimg_utils.get_sleep_state()
    local pos = db.actor:position()
    dwimg_utils.print_dbg("SAVE POSITION %s| %s %s %s |", level.name(), pos.x, pos.y, pos.z)
    if stash_data then
        sleep.stash_save = {}
        sleep.stash_created = true
        sleep.stash_save.level = level.name()
        sleep.stash_save.posX = pos.x
        sleep.stash_save.posY = pos.y
        sleep.stash_save.posZ = pos.z
        sleep.stash_save.position = vector():set(sleep.stash_save.posX or 0, sleep.stash_save.posY or 0,
            sleep.stash_save.posZ or 0)
        sleep.stash_save.level_vert = db.actor:level_vertex_id()
        sleep.stash_save.game_vert = db.actor:game_vertex_id()
        sleep.stash_save.stash_id = stash_data.stash_id
        sleep.type = "stash"
        level.map_add_object_spot_ser(stash_data.stash_id, "ui_pda2_actor_sleep_location", "Respawn")
    else
        sleep.level = level.name()
        sleep.posX = pos.x
        sleep.posY = pos.y
        sleep.posZ = pos.z
        sleep.position = vector():set(sleep.posX or 0, sleep.posY or 0, sleep.posZ or 0)
        sleep.level_vert = db.actor:level_vertex_id()
        sleep.game_vert = db.actor:game_vertex_id()
        sleep.sleep_created = true
        sleep.type = "sleep"
    end
    local save_message = strformat("Respawn point set.", text)
    exec_console_cmd("main_menu off")
    actor_menu.set_msg(1, save_message, 4) 
end

function on_game_load()
	local sleep = dwimg_utils.get_sleep_state()
	if not(sleep.posX or (sleep.stash_save and sleep.stash_save.posX)) and level.name() ~= "fake_start" then
		save_position()
	end
end

local function actor_on_sleep()
    if dwimg_main.config.on_off == 0 then
		return
	end
	if not dwimg_main.config.use_sleep_respawn or has_alife_info("bar_arena_fight") or has_alife_info("bar_arena_start") or dwimg_utils.check_all_lists("ignored_levels", level.name()) then
		return
	end
	local sleep = dwimg_utils.get_sleep_state()
	dwimg_utils.print_dbg("SET POSITION on SLEEP " .. tostring(dwimg_main.config.use_sleep_respawn))
	sleep.sleep_created = true
	save_position()
end

local function actor_on_stash_create(stash_data)
    if dwimg_main.config.on_off == 0 then
		return
	end
    if not(dwimg_main.config.use_stash_respawn) or has_alife_info("bar_arena_fight") or has_alife_info("bar_arena_start") or dwimg_utils.check_all_lists("ignored_levels", level.name()) then
		return
	end
    local sleep = dwimg_utils.get_sleep_state()
    sleep.stash_created = true
    save_position(stash_data)
end

local function actor_on_stash_remove(stash_data)
    if dwimg_main.config.on_off == 0 then
		return
	end
    local sleep = dwimg_utils.get_sleep_state()
    if sleep.stash_save and (stash_data.stash_id == sleep.stash_save.stash_id) then
        sleep.stash_created = false;
        sleep.stash_save = nil
        sleep.type = "sleep"
    end
    if sleep.dropped_stashes and sleep.dropped_stashes[stash_data.stash_id] then
        dwimg_main.send_items_report_news_msg(true, stash_data.stash_id)
        sleep.dropped_stashes[stash_data.stash_id] = nil
    end
end

local function on_before_save_input(flags, typ_, text)
    if dwimg_main.config.on_off == 0 then
		return
	end
	if not dwimg_main.config.use_campfire_respawn or has_alife_info("bar_arena_fight") or has_alife_info("bar_arena_start") or dwimg_utils.check_all_lists("ignored_levels", level.name()) then
		return
	end
    local sleep = dwimg_utils.get_sleep_state()
    local nearby_campfire = bind_campfire.get_nearby_campfire(10, true)
    if not nearby_campfire then
        return
    end
	dwimg_utils.print_dbg("SET POSITION on CAMPFIRE " .. tostring(dwimg_main.config.use_campfire_respawn))
	sleep.sleep_created = true
	save_position()
end

-- ==============================================================
-- TELEPORT TO RESPAWN POINT
-- ==============================================================

function respawn_teleport()
	local sleep = dwimg_utils.get_sleep_state()
	
	if (sleep.posX and sleep.level) or (sleep.stash_save and sleep.stash_save.posX and sleep.stash_save.level) then
		dwimg_utils.print_dbg("TELEPORT")
		if sleep.stash_created and dwimg_main.config.use_stash_respawn then
			ChangeLevel(vector():set(sleep.stash_save.posX, sleep.stash_save.posY, sleep.stash_save.posZ), sleep.stash_save.level_vert,
				sleep.stash_save.game_vert, VEC_ZERO, false)
		else
			ChangeLevel(vector():set(sleep.posX, sleep.posY, sleep.posZ), sleep.level_vert,
				sleep.game_vert, VEC_ZERO, false)
		end
	else
		xr_effects.change_level_now(vector():set(136.32, 28.9, 240.395), 348892, 4920, VEC_ZERO, true) -- hideout in outskirts
	end
end

-- ==============================================================
-- INIT SCRIPT CALLBACKS
-- ==============================================================

function on_game_start()
    RegisterScriptCallback("actor_on_sleep", actor_on_sleep)
    RegisterScriptCallback("actor_on_stash_create", actor_on_stash_create)
    RegisterScriptCallback("actor_on_stash_remove", actor_on_stash_remove)
    RegisterScriptCallback("on_before_save_input", on_before_save_input)
    RegisterScriptCallback("on_game_load", on_game_load)
end