-- ==============================================================
-- LOAD SETTINGS
-- ==============================================================

local function load_settings_money()
	dwimg_main.config.min_money_percentage = dwimg_mcm.get_config("money/min_money_percentage")
	dwimg_main.config.max_money_percentage = dwimg_mcm.get_config("money/max_money_percentage")
	dwimg_main.config.min_money_to_drop_percentage = dwimg_mcm.get_config("money/min_money_to_drop_percentage")
	dwimg_main.config.max_money_to_drop_percentage = dwimg_mcm.get_config("money/max_money_to_drop_percentage")
	dwimg_main.config.min_money_to_keep_inventory = dwimg_mcm.get_config("money/min_money_to_keep_inventory")
	dwimg_main.config.min_money_to_keep_general = dwimg_mcm.get_config("money/min_money_to_keep_general")	
	dwimg_main.config.max_lost_money = dwimg_mcm.get_config("money/max_lost_money")
	dwimg_main.config.money_y_rank = dwimg_mcm.get_config("money/money_y_rank")
	
	if dwimg_main.config.max_money_percentage < dwimg_main.config.min_money_percentage then
		dwimg_main.config.max_money_percentage = dwimg_main.config.min_money_percentage
	end
	if dwimg_main.config.max_money_to_drop_percentage < dwimg_main.config.min_money_to_drop_percentage then
		dwimg_main.config.max_money_to_drop_percentage = dwimg_main.config.min_money_to_drop_percentage
	end
	if dwimg_main.config.min_money_to_keep_general < dwimg_main.config.min_money_to_keep_inventory then
		dwimg_main.config.min_money_to_keep_general = dwimg_main.config.min_money_to_keep_inventory
	end
end

local function load_settings_condition()
	--condition_ga
    dwimg_main.config.min_condition_lose = dwimg_mcm.get_config("condition/condition_ga/min_condition_lose")
    dwimg_main.config.max_condition_lose = dwimg_mcm.get_config("condition/condition_ga/max_condition_lose")
	dwimg_main.config.part_break_chance = dwimg_mcm.get_config("condition/condition_ga/part_break_chance")
	dwimg_main.config.min_weapon_condition = dwimg_mcm.get_config("condition/condition_ga/min_weapon_condition")
	dwimg_main.config.min_armor_condition = dwimg_mcm.get_config("condition/condition_ga/min_armor_condition")
	dwimg_main.config.condition_unequipped = dwimg_mcm.get_config("condition/condition_ga/condition_unequipped")
	dwimg_main.config.spread_weapon_condition = dwimg_mcm.get_config("condition/condition_ga/spread_weapon_condition")
	--condition_o
    dwimg_main.config.min_condition_lose2 = dwimg_mcm.get_config("condition/condition_o/min_condition_lose2")
    dwimg_main.config.max_condition_lose2 = dwimg_mcm.get_config("condition/condition_o/max_condition_lose2")
    dwimg_main.config.condition_melee = dwimg_mcm.get_config("condition/condition_o/condition_melee")	
	dwimg_main.config.condition_perk_artefact = dwimg_mcm.get_config("condition/condition_o/condition_perk_artefact")
	dwimg_main.config.condition_stat_artefact = dwimg_mcm.get_config("condition/condition_o/condition_stat_artefact")
	dwimg_main.config.condition_pelt = dwimg_mcm.get_config("condition/condition_o/condition_pelt")

	if dwimg_main.config.max_condition_lose < dwimg_main.config.min_condition_lose then
		dwimg_main.config.max_condition_lose = dwimg_main.config.min_condition_lose
	end
	if dwimg_main.config.max_condition_lose2 < dwimg_main.config.min_condition_lose2 then
		dwimg_main.config.max_condition_lose2 = dwimg_main.config.min_condition_lose2
	end		
end

local function load_settings_item_loss()
	--lose_keep
	dwimg_main.config.chance_of_losing_guns = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_guns")
	dwimg_main.config.chance_of_losing_guns_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_guns_anti")
    dwimg_main.config.keep_guns_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_guns_chance")
    dwimg_main.config.keep_guns_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_guns_chance_anti")
	dwimg_main.config.chance_of_losing_gun_attachments = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_gun_attachments")
	dwimg_main.config.chance_of_losing_gun_attachments_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_gun_attachments_anti")
    dwimg_main.config.keep_gun_attachment_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_gun_attachment_chance")
    dwimg_main.config.keep_gun_attachment_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_gun_attachment_chance_anti")
	dwimg_main.config.chance_of_losing_outfits = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_outfits")
	dwimg_main.config.chance_of_losing_outfits_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_outfits_anti")
    dwimg_main.config.keep_outfit_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_outfit_chance")
    dwimg_main.config.keep_outfit_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_outfit_chance_anti")
	dwimg_main.config.chance_of_losing_artefacts = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_artefacts")
	dwimg_main.config.chance_of_losing_artefacts_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_artefacts_anti")
	dwimg_main.config.keep_artefact_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_artefact_chance")
	dwimg_main.config.keep_artefact_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_artefact_chance_anti")
	dwimg_main.config.chance_of_losing_devices = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_devices")
	dwimg_main.config.chance_of_losing_devices_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_devices_anti")
	dwimg_main.config.keep_device_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_device_chance")
	dwimg_main.config.keep_device_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_device_chance_anti")
	dwimg_main.config.chance_of_losing_kits = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_kits")
	dwimg_main.config.chance_of_losing_kits_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_kits_anti")
	dwimg_main.config.keep_kits_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_kits_chance")
	dwimg_main.config.keep_kits_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_kits_chance_anti")
	dwimg_main.config.chance_of_losing_tools = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_tools")
	dwimg_main.config.chance_of_losing_tools_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_tools_anti")
	dwimg_main.config.keep_tools_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_tools_chance")
	dwimg_main.config.keep_tools_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_tools_chance_anti")
	dwimg_main.config.chance_of_losing_explosives = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_explosives")
	dwimg_main.config.chance_of_losing_explosives_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_explosives_anti")
    dwimg_main.config.keep_explosives_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_explosives_chance")
    dwimg_main.config.keep_explosives_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_explosives_chance_anti")
	dwimg_main.config.chance_of_losing_ammo = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_ammo")
	dwimg_main.config.chance_of_losing_ammo_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_ammo_anti")
    dwimg_main.config.keep_ammo_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_ammo_chance")
    dwimg_main.config.keep_ammo_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_ammo_chance_anti")
	dwimg_main.config.chance_of_losing_medics = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_medics")
	dwimg_main.config.chance_of_losing_medics_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_medics_anti")
	dwimg_main.config.keep_medics_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_medics_chance")
	dwimg_main.config.keep_medics_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_medics_chance_anti")
	dwimg_main.config.chance_of_losing_items = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_items")
	dwimg_main.config.chance_of_losing_items_anti = dwimg_mcm.get_config("item_loss/lose_keep/chance_of_losing_items_anti")
    dwimg_main.config.keep_misc_items_chance = 100 - dwimg_mcm.get_config("item_loss/lose_keep/keep_misc_items_chance")
    dwimg_main.config.keep_misc_items_chance_anti = dwimg_mcm.get_config("item_loss/lose_keep/keep_misc_items_chance_anti")
	--loss_scaling
	dwimg_main.config.enable_scale = dwimg_mcm.get_config("item_loss/loss_scaling/enable_scale")
	dwimg_main.config.scaling_exponent = dwimg_mcm.get_config("item_loss/loss_scaling/scaling_exponent")
	dwimg_main.config.rank_scale_from = dwimg_mcm.get_config("item_loss/loss_scaling/rank_scale_from")
	dwimg_main.config.rank_scale_until = dwimg_mcm.get_config("item_loss/loss_scaling/rank_scale_until")
	dwimg_main.config.rank_loss_multiplier = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier")
	dwimg_main.config.rank_loss_multiplier_anti = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier_anti")
	dwimg_main.config.rank_loss_multiplier_anti_override = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier_anti_override")
	dwimg_main.config.rank_scale_from2 = dwimg_mcm.get_config("item_loss/loss_scaling/rank_scale_from2")
	dwimg_main.config.rank_scale_until2 = dwimg_mcm.get_config("item_loss/loss_scaling/rank_scale_until2")
	dwimg_main.config.rank_loss_multiplier2 = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier2")
	dwimg_main.config.rank_loss_multiplier_anti2 = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier_anti2")
	dwimg_main.config.rank_loss_multiplier_anti2_override = dwimg_mcm.get_config("item_loss/loss_scaling/rank_loss_multiplier_anti2_override")
	dwimg_main.config.exemption_scale = dwimg_mcm.get_config("item_loss/loss_scaling/exemption_scale")

	if dwimg_main.config.rank_scale_until <= dwimg_main.config.rank_scale_from then
		dwimg_main.config.rank_scale_until = dwimg_main.config.rank_scale_from + 1
	end
	if dwimg_main.config.rank_scale_until2 <= dwimg_main.config.rank_scale_from2 then
		dwimg_main.config.rank_scale_until2 = dwimg_main.config.rank_scale_from2 + 1
	end		
end

local function load_settings_ignore()
	dwimg_main.config.ignore_pda = dwimg_mcm.get_config("ignore/ignore_pda")
	dwimg_main.config.ignore_backpack = dwimg_mcm.get_config("ignore/ignore_backpack")
	dwimg_main.config.ignore_detector = dwimg_mcm.get_config("ignore/ignore_detector")
	dwimg_main.config.ignore_torch_nvg = dwimg_mcm.get_config("ignore/ignore_torch_nvg")
	dwimg_main.config.ignore_knife = dwimg_mcm.get_config("ignore/ignore_knife")
	dwimg_main.config.ignore_axe = dwimg_mcm.get_config("ignore/ignore_axe")
	dwimg_main.config.ignore_binoculars = dwimg_mcm.get_config("ignore/ignore_binoculars")
	dwimg_main.config.ignore_special_equipment = dwimg_mcm.get_config("ignore/ignore_special_equipment")
end

local function load_settings_protection()
	dwimg_main.config.max_rank_exemption = dwimg_mcm.get_config("protection/max_rank_exemption")
	dwimg_main.config.gained_rank_exemption = dwimg_mcm.get_config("protection/gained_rank_exemption")
	dwimg_main.config.max_time_exemption = dwimg_mcm.get_config("protection/max_time_exemption")
	dwimg_main.config.passed_time_exemption = dwimg_mcm.get_config("protection/passed_time_exemption")
	dwimg_main.config.max_rank_exemption2 = dwimg_mcm.get_config("protection/max_rank_exemption2")
	dwimg_main.config.gained_rank_exemption2 = dwimg_mcm.get_config("protection/gained_rank_exemption2")
	dwimg_main.config.max_time_exemption2 = dwimg_mcm.get_config("protection/max_time_exemption2")
	dwimg_main.config.passed_time_exemption2 = dwimg_mcm.get_config("protection/passed_time_exemption2")
	dwimg_main.config.exemption_everything = dwimg_mcm.get_config("protection/exemption_everything")	
	dwimg_main.config.exemption_money = dwimg_mcm.get_config("protection/exemption_money")
	dwimg_main.config.exemption_guns = dwimg_mcm.get_config("protection/exemption_guns")
	exemption_gun_attachements = dwimg_mcm.get_config("protection/exemption_gun_attachements")
	dwimg_main.config.exemption_outfits = dwimg_mcm.get_config("protection/exemption_outfits")
	exemption_artefacts = dwimg_mcm.get_config("protection/exemption_artefacts")
	exemption_device = dwimg_mcm.get_config("protection/exemption_device")
	exemption_kit = dwimg_mcm.get_config("protection/exemption_kit")
	exemption_tools = dwimg_mcm.get_config("protection/exemption_tools")
	exemption_explosives = dwimg_mcm.get_config("protection/exemption_explosives")
	dwimg_main.config.exemption_ammo = dwimg_mcm.get_config("protection/exemption_ammo")
	dwimg_main.config.exemption_medics = dwimg_mcm.get_config("protection/exemption_medics")
	dwimg_main.config.exemption_misc = dwimg_mcm.get_config("protection/exemption_misc")
end

local function load_settings_item_punish()
	--item_break
	dwimg_main.config.broken_gun_chance = dwimg_mcm.get_config("item_punish/item_break/broken_gun_chance")
	dwimg_main.config.broken_armor_chance = dwimg_mcm.get_config("item_punish/item_break/broken_armor_chance")
	dwimg_main.config.keep_gun_armor_parts_chance = dwimg_mcm.get_config("item_punish/item_break/keep_gun_armor_parts_chance")
	dwimg_main.config.keep_upgrade_chance = dwimg_mcm.get_config("item_punish/item_break/keep_upgrade_chance")
	dwimg_main.config.broken_device_chance = dwimg_mcm.get_config("item_punish/item_break/broken_device_chance")
	dwimg_main.config.keep_device_part_chance = dwimg_mcm.get_config("item_punish/item_break/keep_device_part_chance")
	--break_o
	dwimg_main.config.remove_upgrade_chance = dwimg_mcm.get_config("item_punish/break_o/remove_upgrade_chance")
	dwimg_main.config.downgrade_chance = dwimg_mcm.get_config("item_punish/break_o/downgrade_chance")
end

local function load_settings_character()
	dwimg_main.config.quest_fail_chance = dwimg_mcm.get_config("character/quest_fail_chance")
	dwimg_main.config.rank_loss = dwimg_mcm.get_config("character/rank_loss")
	dwimg_main.config.goodwill_loss_flat = dwimg_mcm.get_config("character/goodwill_loss_flat")
	dwimg_main.config.goodwill_loss_percent = dwimg_mcm.get_config("character/goodwill_loss_percent")
	dwimg_main.config.min_goodwill = dwimg_mcm.get_config("character/min_goodwill")
	dwimg_main.config.goodwill_friends = dwimg_mcm.get_config("character/goodwill_friends")
	dwimg_main.config.goodwill_loss_flat_f = dwimg_mcm.get_config("character/goodwill_loss_flat_f") 		
	dwimg_main.config.goodwill_loss_percent_f = dwimg_mcm.get_config("character/goodwill_loss_percent_f")	
	dwimg_main.config.min_goodwill_f = dwimg_mcm.get_config("character/min_goodwill_f")
	dwimg_main.config.goodwill_neutrals = dwimg_mcm.get_config("character/goodwill_neutrals")
	dwimg_main.config.goodwill_loss_flat_n = dwimg_mcm.get_config("character/goodwill_loss_flat_n") 		
	dwimg_main.config.goodwill_loss_percent_n = dwimg_mcm.get_config("character/goodwill_loss_percent_n")	
	dwimg_main.config.min_goodwill_n = dwimg_mcm.get_config("character/min_goodwill_n")
	dwimg_main.config.goodwill_enemies = dwimg_mcm.get_config("character/goodwill_enemies")
	dwimg_main.config.goodwill_loss_flat_e = dwimg_mcm.get_config("character/goodwill_loss_flat_e") 		
	dwimg_main.config.goodwill_loss_percent_e = dwimg_mcm.get_config("character/goodwill_loss_percent_e")	
	dwimg_main.config.min_goodwill_e = dwimg_mcm.get_config("character/min_goodwill_e")
end

local function load_settings_day_time()
	--time_skip
    dwimg_main.config.min_time_skip = dwimg_mcm.get_config("day_time/time_skip/min_time_skip")
    dwimg_main.config.max_time_skip = dwimg_mcm.get_config("day_time/time_skip/max_time_skip")
    dwimg_main.config.enable_wake_hours = dwimg_mcm.get_config("day_time/time_skip/enable_wake_hours")
    dwimg_main.config.min_wake_hour = dwimg_mcm.get_config("day_time/time_skip/min_wake_hour")
    dwimg_main.config.max_wake_hour = dwimg_mcm.get_config("day_time/time_skip/max_wake_hour")
	--sat_thirst
    dwimg_main.config.satiety_loss_per_hour = dwimg_mcm.get_config("day_time/sat_thirst/satiety_loss_per_hour")
	dwimg_main.config.min_satiety = dwimg_mcm.get_config("day_time/sat_thirst/min_satiety")
	dwimg_main.config.min_thirst = dwimg_mcm.get_config("day_time/sat_thirst/min_thirst")
	
	if dwimg_main.config.max_time_skip < dwimg_main.config.min_time_skip then
		dwimg_main.config.max_time_skip = dwimg_main.config.min_time_skip
	end
	if dwimg_main.config.min_time_skip + dwimg_main.config.min_time_skip > 0 then
		dwimg_main.config.enable_time_forward = true
	else
		dwimg_main.config.enable_time_forward = false
	end
end

local function load_settings_old_stuff()
    dwimg_main.config.min_health = dwimg_mcm.get_config("old_stuff/min_health")
    dwimg_main.config.max_health = dwimg_mcm.get_config("old_stuff/max_health")
    dwimg_main.config.full_heal_chance = dwimg_mcm.get_config("old_stuff/full_heal_chance")
    dwimg_main.config.full_satiety_chance = dwimg_mcm.get_config("old_stuff/full_satiety_chance")
    dwimg_main.config.remove_previous_stash = dwimg_mcm.get_config("old_stuff/remove_previous_stash")
    dwimg_main.config.use_campfire_respawn = dwimg_mcm.get_config("old_stuff/use_campfire_respawn")
    dwimg_main.config.use_stash_respawn = dwimg_mcm.get_config("old_stuff/use_stash_respawn")
    dwimg_main.config.use_sleep_respawn = dwimg_mcm.get_config("old_stuff/use_sleep_respawn")

	if dwimg_main.config.max_health < dwimg_main.config.min_health then
		dwimg_main.config.max_health = dwimg_main.config.min_health
	end
end

-- --------------------------------------------------------------
-- INIT EXEMPTIONS
-- --------------------------------------------------------------

local function init_protections()
	dwimg_main.rule_a_prot = {}
	dwimg_main.rule_b_prot = {}
	if dwimg_main.config.exemption_guns == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.GUN] = true
	elseif dwimg_main.config.exemption_guns == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.GUN] = true
	end
	if exemption_gun_attachements == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.ATTACHEMENT_WPN] = true
	elseif exemption_gun_attachements == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.ATTACHEMENT_WPN] = true
	end
	if dwimg_main.config.exemption_outfits == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.ARMOR] = true
	elseif dwimg_main.config.exemption_outfits == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.ARMOR] = true
	end
	if exemption_artefacts == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.ARTEFACT_PERK] = true
		dwimg_main.rule_a_prot[dwimg_lists.item_type.ARTEFACT_STAT] = true
		dwimg_main.rule_a_prot[dwimg_lists.item_type.PELT] = true
	elseif exemption_artefacts == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.ARTEFACT_PERK] = true
		dwimg_main.rule_b_prot[dwimg_lists.item_type.ARTEFACT_STAT] = true
		dwimg_main.rule_b_prot[dwimg_lists.item_type.PELT] = true
	end
	if exemption_device == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.UPGRADED] = true
	elseif exemption_device == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.UPGRADED] = true
	end
	if exemption_kit == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.KIT] = true
	elseif exemption_kit == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.KIT] = true
	end
	if exemption_tools == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.TOOL] = true
	elseif exemption_tools == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.TOOL] = true
	end
	if exemption_explosives == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.EXPLOSIVE] = true
	elseif exemption_explosives == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.EXPLOSIVE] = true
	end
	if dwimg_main.config.exemption_ammo == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.AMMO] = true
	elseif dwimg_main.config.exemption_ammo == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.AMMO] = true
	end
	if dwimg_main.config.exemption_medics == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.MEDICAL] = true
	elseif dwimg_main.config.exemption_medics == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.MEDICAL] = true
	end
	if dwimg_main.config.exemption_misc == 1 then
		dwimg_main.rule_a_prot[dwimg_lists.item_type.MISC] = true
	elseif dwimg_main.config.exemption_misc == 2 then
		dwimg_main.rule_b_prot[dwimg_lists.item_type.MISC] = true
	end
end

-- ==============================================================
-- PRESETS
-- ==============================================================

function init_preset_filter()
	local filter_list = {}
	local to_filter = {"money", "condition", "item_loss", "ignore", "protection", "item_punish", "character", "day_time", "old_stuff"}
	for i=1, #to_filter do
		if dwimg_mcm.get_config("presets/custom_presets/cst_preset_" .. to_filter[i]) == true then
			filter_list[to_filter[i]] = true
			dwimg_utils.print_dbg("Added to filter list " .. to_filter[i])
		end	
		i = i+1
	end
	return filter_list
end

function check_presets()
	dwimg_mcm.preset_backup()
	
	--load custom presets
	if dwimg_mcm.get_config("presets/custom_presets/load_preset") then  
		dwimg_mcm.handle_preset(dwimg_mcm.get_config("presets/custom_presets/chosen_preset"), 'l', dwimg_mcm.on_mcm_load()["gr"], "", init_preset_filter(), false)
	end	
	
	--load default presets
	local def_presets = {"money", "condition", "item_loss_basic", "item_loss_core", "item_loss_scaling", "item_punish", "ignore", "protection", "character"}
	for i=1, #def_presets do
		local curr_preset_val =  dwimg_mcm.get_config("presets/default_presets/def_preset_" .. def_presets[i])
		if curr_preset_val ~= "n" then
			dwimg_mcm.load_def_preset(curr_preset_val)
		end
		i = i+1
	end
	
	--save custom presets
	if dwimg_mcm.get_config("presets/custom_presets/save_preset") then
		dwimg_mcm.handle_preset(dwimg_mcm.get_config("presets/custom_presets/chosen_preset"), 's', dwimg_mcm.on_mcm_load()["gr"], "", init_preset_filter(), false)
	end
	dwimg_mcm.set_config("presets/custom_presets/save_preset", false)
	dwimg_mcm.set_config("presets/custom_presets/load_preset", false)
end

-- ==============================================================
-- SCRIPT CALLBACKS
-- ==============================================================

function on_game_start()
    RegisterScriptCallback("on_option_change", load_settings)
    RegisterScriptCallback("on_game_load", load_settings)
end

function load_settings()
	check_presets()

	if dwimg_mcm.get_config("debug/print_preset") then
		dwimg_utils.print_dbg("Start of preset copy paste")
	end
	load_settings_money()
	load_settings_condition()
	load_settings_item_loss()
	load_settings_ignore()
	load_settings_protection()
	load_settings_item_punish()
	load_settings_character()
	load_settings_day_time()
	load_settings_old_stuff()
	if dwimg_mcm.get_config("debug/print_preset") then
		dwimg_utils.print_dbg("End of preset copy paste")
	end

    dwimg_main.config.display_issue = dwimg_mcm.get_config("debug/display_issue")
    dwimg_main.config.use_dwimglog = dwimg_mcm.get_config("debug/use_dwimglog")

	init_protections()
end