-- ==============================================================
-- LOAD SETTINGS
-- ==============================================================

function load_all_settings(curr_setting_table, curr_setting_string)
	local _curr_setting_string = curr_setting_string
	dwimg_utils.print_dbg("Started handle load setting curr_string " .. curr_setting_string)
	if  curr_setting_table["gr"] then
		_curr_setting_string = _curr_setting_string .. curr_setting_table["id"] .. "/"
		--dwimg_utils.print_dbg("Recursion curr_string " .. _curr_setting_string)
		load_all_settings(curr_setting_table["gr"], _curr_setting_string)
	else
		if curr_setting_table["id"] and curr_setting_table["type"] ~= "desc" then
			_curr_setting_string = _curr_setting_string .. curr_setting_table["id"]
			dwimg_utils.print_dbg("Load setting " .. curr_setting_table["id"])
			dwimg_main.config[curr_setting_table["id"]] = dwimg_mcm.get_config(_curr_setting_string)
		else
			for i=1, #curr_setting_table do
				--dwimg_utils.print_dbg("Recursion curr_string " .. _curr_setting_string)
				load_all_settings(curr_setting_table[i], _curr_setting_string)				
				i = i+1
			end
		end
	end
end

function handle_setting_corrections()
	if dwimg_main.config.max_money_percentage < dwimg_main.config.min_money_percentage then
		dwimg_main.config.max_money_percentage = dwimg_main.config.min_money_percentage
	end
	if dwimg_main.config.max_money_to_drop_percentage < dwimg_main.config.min_money_to_drop_percentage then
		dwimg_main.config.max_money_to_drop_percentage = dwimg_main.config.min_money_to_drop_percentage
	end
	if dwimg_main.config.min_money_to_keep_general < dwimg_main.config.min_money_to_keep_inventory then
		dwimg_main.config.min_money_to_keep_general = dwimg_main.config.min_money_to_keep_inventory
	end	
	if dwimg_main.config.max_condition_lose < dwimg_main.config.min_condition_lose then
		dwimg_main.config.max_condition_lose = dwimg_main.config.min_condition_lose
	end
	if dwimg_main.config.max_condition_lose2 < dwimg_main.config.min_condition_lose2 then
		dwimg_main.config.max_condition_lose2 = dwimg_main.config.min_condition_lose2
	end
	if dwimg_main.config.rank_scale_until <= dwimg_main.config.rank_scale_from then
		dwimg_main.config.rank_scale_until = dwimg_main.config.rank_scale_from + 1
	end
	if dwimg_main.config.rank_scale_until2 <= dwimg_main.config.rank_scale_from2 then
		dwimg_main.config.rank_scale_until2 = dwimg_main.config.rank_scale_from2 + 1
	end
	if dwimg_main.config.min_time_skip + dwimg_main.config.min_time_skip > 0 then
		dwimg_main.config.enable_time_forward = true
	else
		dwimg_main.config.enable_time_forward = false
	end
	if dwimg_main.config.max_health < dwimg_main.config.min_health then
		dwimg_main.config.max_health = dwimg_main.config.min_health
	end
	local sleep = dwimg_utils.get_sleep_state()
	if sleep.on_off == nil then
		dwimg_utils.print_dbg("Get default on_off with " .. dwimg_main.config.on_off_def)
		dwimg_main.config.on_off = dwimg_main.config.on_off_def
	end
	dwimg_utils.print_dbg("Set save game on_off with " .. dwimg_main.config.on_off)
	sleep.on_off = dwimg_main.config.on_off
end

-- --------------------------------------------------------------
-- INIT EXEMPTIONS
-- --------------------------------------------------------------

local function init_protections()
	dwimg_items.rule_a_prot = {}
	dwimg_items.rule_b_prot = {}
	if dwimg_main.config.exemption_guns == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.GUN] = true
	elseif dwimg_main.config.exemption_guns == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.GUN] = true
	end
	if exemption_gun_attachements == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.ATTACHEMENT_WPN] = true
	elseif exemption_gun_attachements == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.ATTACHEMENT_WPN] = true
	end
	if dwimg_main.config.exemption_outfits == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.ARMOR] = true
	elseif dwimg_main.config.exemption_outfits == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.ARMOR] = true
	end
	if dwimg_main.config.exemption_artefacts == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.ARTEFACT_PERK] = true
		dwimg_items.rule_a_prot[dwimg_lists.item_type.ARTEFACT_STAT] = true
		dwimg_items.rule_a_prot[dwimg_lists.item_type.PELT] = true
	elseif dwimg_main.config.exemption_artefacts == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.ARTEFACT_PERK] = true
		dwimg_items.rule_b_prot[dwimg_lists.item_type.ARTEFACT_STAT] = true
		dwimg_items.rule_b_prot[dwimg_lists.item_type.PELT] = true
	end
	if dwimg_main.config.exemption_device == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.UPGRADED] = true
	elseif dwimg_main.config.exemption_device == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.UPGRADED] = true
	end
	if dwimg_main.config.exemption_kit == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.KIT] = true
	elseif dwimg_main.config.exemption_kit == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.KIT] = true
	end
	if dwimg_main.config.exemption_tools == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.TOOL] = true
	elseif dwimg_main.config.exemption_tools == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.TOOL] = true
	end
	if dwimg_main.config.exemption_explosives == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.EXPLOSIVE] = true
	elseif dwimg_main.config.exemption_explosives == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.EXPLOSIVE] = true
	end
	if dwimg_main.config.exemption_ammo == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.AMMO] = true
	elseif dwimg_main.config.exemption_ammo == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.AMMO] = true
	end
	if dwimg_main.config.exemption_medics == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.MEDICAL] = true
	elseif dwimg_main.config.exemption_medics == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.MEDICAL] = true
	end
	if dwimg_main.config.exemption_misc == 1 then
		dwimg_items.rule_a_prot[dwimg_lists.item_type.MISC] = true
	elseif dwimg_main.config.exemption_misc == 2 then
		dwimg_items.rule_b_prot[dwimg_lists.item_type.MISC] = true
	end
end

-- ==============================================================
-- PRESETS
-- ==============================================================

function init_preset_filter()
	local filter_list = {}
	local to_filter = {"money", "condition", "item_loss", "ignore", "protection", "item_punish", "character", "day_time", "old_stuff"}
	for i=1, #to_filter do
		if dwimg_mcm.get_config("presets/custom_presets/cst_preset_" .. to_filter[i]) == true then
			filter_list[to_filter[i]] = true
			dwimg_utils.print_dbg("Added to filter list " .. to_filter[i])
		end	
		i = i+1
	end
	return filter_list
end

function check_presets()
	dwimg_mcm.preset_backup()
	
	--load custom presets
	if dwimg_mcm.get_config("presets/custom_presets/load_preset") then  
		dwimg_mcm.handle_preset(dwimg_mcm.get_config("presets/custom_presets/chosen_preset"), 'l', dwimg_mcm.on_mcm_load()["gr"], "", init_preset_filter(), false)
	end
	
	--load default presets
	local def_presets = {"money", "condition", "item_loss_basic", "item_loss_core", "item_loss_scaling", "item_punish", "ignore", "protection", "character"}
	for i=1, #def_presets do
		local curr_preset_val =  dwimg_mcm.get_config("presets/default_presets/def_preset_" .. def_presets[i])
		if curr_preset_val ~= "n" then
			dwimg_mcm.load_def_preset(curr_preset_val)
		end
		i = i+1
	end
	
	--save custom presets
	if dwimg_mcm.get_config("presets/custom_presets/save_preset") then
		dwimg_mcm.handle_preset(dwimg_mcm.get_config("presets/custom_presets/chosen_preset"), 's', dwimg_mcm.on_mcm_load()["gr"], "", init_preset_filter(), false)
	end
	dwimg_mcm.set_config("presets/custom_presets/save_preset", false)
	dwimg_mcm.set_config("presets/custom_presets/load_preset", false)
end

-- ==============================================================
-- REMOVAL
-- ==============================================================

local function remove_mod()
	local type = dwimg_mcm.get_config("main_settings/removal_type")
	local sleep = dwimg_utils.get_sleep_state()
	if type >= 1 then
		for stash_id, _ in pairs(sleep.dropped_stashes) do
			level.map_remove_object_spot(stash_id, "treasure")
		end
	end
	if type >=2 then
		for stash_id, _ in pairs(sleep.dropped_stashes) do
			sleep.dropped_stashes[stash_id] = nil
			alife_release_id(stash_id)
		end		
	end
	if type >=3 then
		alife_storage_manager.get_state().dude_where_is_my_gear = {removed = true}
		dwimg_main.config.on_off = 0
		dwimg_mcm.set_config("main_settings/on_off", 0)
		dwimg_utils.print_dbg("Removed!!")
	end
end

-- ==============================================================
-- SOULSLIKE OVERWRITE
-- ==============================================================

function soulslike.IsSoulslikeMode()
	if alife_storage_manager.get_state().enable_soulslike_mode == true then
		if dwimg_mcm.get_config("main_settings/on_off") == 0 then
			return true
		else
			if dwimg_mcm.get_config("main_settings/soulslike_overwrite") == 0 then
				dwimg_main.config.on_off = 0
				dwimg_mcm.set_config("main_settings/on_off", 0)
				return true
			else
				return false
			end
		end
	else
		return false
	end
end

-- ==============================================================
-- SCRIPT CALLBACKS
-- ==============================================================

function on_game_start()
    RegisterScriptCallback("on_option_change", load_settings)
    RegisterScriptCallback("on_game_load", load_settings_alt)
end

function load_settings()
	--check for removal
	if dwimg_mcm.get_config("main_settings/removal_type") ~= 0 and dwimg_mcm.get_config("main_settings/confirm_removal") == true then
		remove_mod()
	end
	if dwimg_mcm.get_config("main_settings/removal_type") ~= 0 or dwimg_mcm.get_config("main_settings/confirm_removal") == true then
		dwimg_mcm.set_config("main_settings/removal_type", 0)
		dwimg_mcm.set_config("main_settings/confirm_removal", false)
	end
	local sleep = dwimg_utils.get_sleep_state()
	if sleep.removed == true then
		dwimg_main.config.on_off = 0
		dwimg_mcm.set_config("main_settings/on_off", 0)		
		return
	end

	--load settings
	check_presets()

	if dwimg_mcm.get_config("debug/print_preset") then
		dwimg_utils.print_dbg("Start of preset copy paste")
	end

	load_all_settings(dwimg_mcm.on_mcm_load()["gr"], "")

	if dwimg_mcm.get_config("debug/print_preset") then
		dwimg_utils.print_dbg("End of preset copy paste")
	end

    --dwimg_main.config.display_issue = dwimg_mcm.get_config("debug/display_issue")
	handle_setting_corrections()
	init_protections()
	dwimg_items.settings_loaded()
end

function load_settings_alt()
	--init default on_off
	local sleep = dwimg_utils.get_sleep_state()
	if sleep.on_off and dwimg_mcm then
		dwimg_utils.print_dbg("Get save game on_off with " .. sleep.on_off)
		dwimg_mcm.set_config("main_settings/on_off", sleep.on_off)
	end
	if dwimg_mcm.get_config("main_settings/on_off") ~=0 then
		load_settings()
	else
		dwimg_main.config.on_off = 0
	end
end