continue_soulslike = 0
cap_obj = nil
souls_stash = nil
souls_id = 0

-- ==============================================================
-- SOULSLIKE SCENARIO
-- ==============================================================

_oldsoul_is_soulslike = soulslike.IsSoulslikeMode
function soulslike.IsSoulslikeMode()
    if dwimg_mcm.get_config("main_settings/on_off") == 2 and dwimg_mcm.get_config("main_settings/force_soulslike") == true then
        return true
    else
        return _oldsoul_is_soulslike
    end
end

_oldsoul_clear = soulslike_classes.TimedQueue.Clear
function soulslike_classes.TimedQueue:Clear()
    dwimg_utils.print_dbg("dwimg soul ended without/after scenario")
    continue_soulslike = 2
    _oldsoul_clear(self)
end

function overwrite_souls_functions()
    dwimg_utils.print_dbg("dwimg soul overwritten")

    local _oldsoul_OnDeath = cap_obj.OnDeath
    function cap_obj:OnDeath()
        dwimg_utils.print_dbg("dwimg soul summoned")
        if dwimg_mcm.get_config("main_settings/on_off") == 2 and (dwimg_mcm.get_config("main_settings/use_soulslike_ambush") == false and dwimg_mcm.get_config("main_settings/use_soulslike_stalker_looter") == false) then
            dwimg_utils.print_dbg("dwimg soul unnecessary!!")
            return
        else
            _oldsoul_OnDeath(self)
        end
    end

    local _oldsoul_HealActor = cap_obj.HealActor
    function cap_obj:HealActor()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_HealActor(self)
        end
    end

    local _oldsoul_ApplyRankLoss = cap_obj.ApplyRankLoss
    function cap_obj:ApplyRankLoss()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_ApplyRankLoss(self)
        end
    end

    local _oldsoul_ApplyReputationLoss = cap_obj.ApplyReputationLoss
    function cap_obj:ApplyReputationLoss()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_ApplyReputationLoss(self)
        end
    end

    local _oldsoul_ApplyTransferItemsPreConditions = cap_obj.ApplyTransferItemsPreConditions
    function cap_obj:ApplyTransferItemsPreConditions()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_ApplyTransferItemsPreConditions(self)
        end
    end

    local _oldsoul_CreateStash = cap_obj.CreateStash
    function cap_obj:CreateStash()
        souls_stash = _oldsoul_CreateStash(self)
        return souls_stash
    end

    local _oldsoul_TransferItem = cap_obj.TransferItem
    function cap_obj:TransferItem(item, container, looter)
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_TransferItem(self, item, container, looter)
        end
    end

    local _oldsoul_ApplyMoneyLoss = cap_obj.ApplyMoneyLoss
    function cap_obj:ApplyMoneyLoss()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_ApplyMoneyLoss(self)
        end
    end

    local _oldsoul_RespawnActor = cap_obj.RespawnActor
    function cap_obj:RespawnActor()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            continue_soulslike = 2            
            return
        else
            _oldsoul_RespawnActor(self)
           continue_soulslike = 2
        end
    end

    local _oldsoul_SpawnAmbush = cap_obj.SpawnAmbush
    function cap_obj:SpawnAmbush()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 and dwimg_mcm.get_config("main_settings/use_soulslike_ambush") == false then
            dwimg_utils.print_dbg("dwimg soul spawn no ambush")
            return
        else
            dwimg_utils.print_dbg("dwimg soul spawn ambush")
            _oldsoul_SpawnAmbush(self)
        end
    end

    local _oldsoul_OnRespawn = cap_obj.OnRespawn
    function cap_obj:OnRespawn()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            cap_obj:SpawnAmbush()
            return
        else
            _oldsoul_OnRespawn(self)
        end
    end

    local _oldsoul_GiveFoodAndWater = cap_obj.GiveFoodAndWater
    function cap_obj:GiveFoodAndWater()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_GiveFoodAndWater(self)
        end
    end

    local _oldsoul_GiveOutfit = cap_obj.GiveOutfit
    function cap_obj:GiveOutfit()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_GiveOutfit(self)
        end
    end

    local _oldsoul_GiveMask = cap_obj.GiveMask
    function cap_obj:GiveMask()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_GiveMask(self)
        end
    end

    local _oldsoul_SendWakeupMessage = cap_obj.SendWakeupMessage
    function cap_obj:SendWakeupMessage()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_SendWakeupMessage(self)
        end
    end

    local _oldsoul_force_save = cap_obj.force_save
    function cap_obj:force_save()
        if dwimg_mcm.get_config("main_settings/on_off") == 2 then
            return
        else
            _oldsoul_force_save(self)
        end
    end
end

_oldsoul_create_by_id = soulslike_scenario_logic_factory.create_by_id
function soulslike_scenario_logic_factory.create_by_id(scenario_id, state)
    cap_obj = _oldsoul_create_by_id(scenario_id, state)
    overwrite_souls_functions()
    souls_id = scenario_id
    return cap_obj
end

_oldsoul_create_new = soulslike_scenario_logic_factory.create_new
function soulslike_scenario_logic_factory.create_new(hits)
    cap_obj =  _oldsoul_create_new(hits)
    dwimg_utils.print_dbg("dwimg soul nilled")
    soul_looter = cap_obj.logic_state.looter_id and level.object_by_id(cap_obj.logic_state.looter_id) or nil
    souls_stash = nil
    return cap_obj
end

-- ==============================================================
-- SOULSLIKE SLEEP DIALOG
-- ==============================================================

_InitControls = ui_sleep_dialog.UISleep.InitControls
_oldsoul_InitControls = soulslike_sleep_dialog.ui_sleep_dialog.UISleep.InitControls
function ui_sleep_dialog.UISleep.InitControls(self)
    if dwimg_mcm.get_config("main_settings/on_off") == 2 and not(dwimg_main.config.use_soulslike_respawn_point) then
        _InitControls(self)
        return
    else
        _oldsoul_InitControls(self)
    end   
end

_OnButtonSleep = ui_sleep_dialog.UISleep.OnButtonSleep
_oldsoul_OnButtonSleep = ui_sleep_dialog.UISleep.OnButtonSleep
function ui_sleep_dialog.UISleep.OnButtonSleep(self) 
    if dwimg_mcm.get_config("main_settings/on_off") == 2 and not(dwimg_main.config.use_soulslike_respawn_point) then
        _OnButtonSleep(self)
        return
    else
        _oldsoul_OnButtonSleep(self)
    end  
end

_oldsoul_OnButtonSetSpawn = ui_sleep_dialog.UISleep.OnButtonSetSpawn
function ui_sleep_dialog.UISleep:OnButtonSetSpawn()
    if dwimg_mcm.get_config("main_settings/on_off") == 2 and dwimg_main.config.use_soulslike_respawn_point then
        dwimg_respawn.save_position()
        return
    else
        _oldsoul_OnButtonSetSpawn(self)
    end  
end