-- ==============================================================
-- RESPAWN AFTER GAME LOAD
-- ==============================================================

-- deletes old stashes
local function handle_stashes()
	local sleep = dwimg_utils.get_sleep_state()
	if dwimg_main.config.remove_previous_stash == 0 then
		return
	end
	while true do
		local list_length = 0
		local oldest_stash_id = nil
		local oldest_stash_time = nil
		for stash_id, _ in pairs(sleep.dropped_stashes) do
			dwimg_utils.print_dbg("Loop: " .. tostring(stash_id) .. " with time " .. tostring(sleep.dropped_stashes[stash_id]["time"]))
			list_length = list_length + 1
			if oldest_stash_time == nil or oldest_stash_time > sleep.dropped_stashes[stash_id]["time"] then
				oldest_stash_time = sleep.dropped_stashes[stash_id]["time"]
				oldest_stash_id = stash_id
				dwimg_utils.print_dbg("New oldest stash: " .. tostring(oldest_stash_id))
			end
		end
		if list_length <= dwimg_main.config.remove_previous_stash then
			dwimg_utils.print_dbg("Not enough stashes: " .. tostring(list_length) .. " / " .. tostring(dwimg_main.config.remove_previous_stash))
			return
		end
		if oldest_stash_id == nil then
			dwimg_utils.print_dbg("oldest stash is nil")
			return			
		end
		dwimg_utils.print_dbg("Too many stashes: " .. tostring(list_length) .. " / " .. tostring(dwimg_main.config.remove_previous_stash))
		dwimg_utils.print_dbg("Delete oldest stash(id): " .. tostring(oldest_stash_id) .. " of " .. tostring(list_length) .. " in total.")
		sleep.dropped_stashes[oldest_stash_id] = nil
		level.map_remove_object_spot(oldest_stash_id, "treasure")
		alife_release_id(oldest_stash_id)
	end
end

function actor_on_movement_changed()
	bind_stalker_ext.invulnerable_time = time_global() - 1
	db.actor.radiation = 0
	if zzz_player_injuries then
		zzz_player_injuries.health.head=zzz_player_injuries.maxhp.head
		zzz_player_injuries.health.torso=zzz_player_injuries.maxhp.torso
		zzz_player_injuries.health.leftarm=zzz_player_injuries.maxhp.leftarm
		zzz_player_injuries.health.rightarm=zzz_player_injuries.maxhp.rightarm
		zzz_player_injuries.health.leftleg=zzz_player_injuries.maxhp.leftleg
		zzz_player_injuries.health.rightleg=zzz_player_injuries.maxhp.rightleg
	end
	dwimg_utils.print_dbg("No longer invincible")
	UnregisterScriptCallback("actor_on_movement_changed",actor_on_movement_changed)	
end

-- sets stats (e.g. health) and re-inits some variables 
function actor_on_first_update()
    if dwimg_main.config.on_off == 0 then
		return
	end
    local sleep = dwimg_utils.get_sleep_state()
	if sleep.dead then
		dwimg_utils.print_dbg("No longer an undead first update")
		bind_stalker_ext.invulnerable_time = time_global() + 999999
		db.actor.bleeding = 1
		db.actor.health = sleep.healing
		db.actor.psy_health = 1
		db.actor.power = 1
		db.actor.radiation = 0
		db.actor:set_health_ex(sleep.healing)
		if zzz_player_injuries then
			zzz_player_injuries.health.head=zzz_player_injuries.maxhp.head
			zzz_player_injuries.health.torso=zzz_player_injuries.maxhp.torso
			zzz_player_injuries.health.leftarm=zzz_player_injuries.maxhp.leftarm
			zzz_player_injuries.health.rightarm=zzz_player_injuries.maxhp.rightarm
			zzz_player_injuries.health.leftleg=zzz_player_injuries.maxhp.leftleg
			zzz_player_injuries.health.rightleg=zzz_player_injuries.maxhp.rightleg
		end

		if sleep.health_status_msg and sleep.wounds_status_msg then
			--db.actor:give_game_news("Recovery", sleep.wounds_status_msg .. sleep.health_status_msg, "ui_inGame2_neutral_2_mask", 0, 20000)
		end
		
		if not ((db.actor:character_rank() - sleep.rank < dwimg_main.config.gained_rank_exemption) or (dwimg_main.config.passed_time_exemption > (dwimg_utils.get_game_seconds() - sleep.time)/3600)) then
			dwimg_utils.print_dbg("New grace period")
			sleep.rank = db.actor:character_rank()
			sleep.time = dwimg_utils.get_game_seconds()
		end
		
		handle_stashes()
        -- db.actor:give_game_news("Severe Injured", sleep.health_status_msg, "ui_inGame2_neutral_2_mask", 5000, 20000)			

		--get_console():execute("hud_draw on")
		sleep.dead = false
		dwimg_utils.print_dbg("No longer undead")
		RegisterScriptCallback("actor_on_movement_changed",actor_on_movement_changed)
	end
end

-- ==============================================================
-- INIT SCRIPT CALLBACKS
-- ==============================================================

function on_game_start()
	RegisterScriptCallback("actor_on_first_update",actor_on_first_update)
end